# ----------------------------------------
# Created on: Tue Feb 28 15:07:45 2023
# Auto generated by Pango
# ----------------------------------------

vsim  -voptargs="+acc" -L work wino_tb
add wave *
view wave
view structure
view signals

run 100000ns

# ----------------------------------------
