# ----------------------------------------
# Created on: Tue Feb 28 15:07:45 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vlog   "C:/Users/FH/Desktop/wino/source/Desktop/winograd_d_fixpt.v" -work work
vlog   "C:/Users/FH/Desktop/wino/source/Desktop/wino_tb.v" -work work

# ----------------------------------------
