// -------------------------------------------------------------
// 
// File Name: C:\Users\FH\Documents\matlab_2019a\bin\codegen\winograd_d\hdlsrc\winograd_d_fixpt.v
// Created: 2023-02-28 11:17:25
// 
// Generated by MATLAB 9.6, MATLAB Coder 4.2 and HDL Coder 3.14
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: winograd_d_fixpt
// Source Path: winograd_d_fixpt
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module winograd_d_fixpt
          (k1,
           k2,
           k3,
           k4,
           k5,
           k6,
           k7,
           k8,
           k9,
           k10,
           k11,
           k12,
           k13,
           k14,
           k15,
           k16,
           w1,
           w2,
           w3,
           w4,
           w5,
           w6,
           w7,
           w8,
           w9,
           R1,
           R2,
           R3,
           R4);


  input   signed [13:0] k1;  // sfix14_En5
  input   signed [13:0] k2;  // sfix14_En5
  input   signed [13:0] k3;  // sfix14_En5
  input   signed [13:0] k4;  // sfix14_En5
  input   signed [13:0] k5;  // sfix14_En5
  input   signed [13:0] k6;  // sfix14_En5
  input   signed [13:0] k7;  // sfix14_En5
  input   signed [13:0] k8;  // sfix14_En5
  input   signed [13:0] k9;  // sfix14_En5
  input   signed [13:0] k10;  // sfix14_En5
  input   signed [13:0] k11;  // sfix14_En5
  input   signed [13:0] k12;  // sfix14_En5
  input   signed [13:0] k13;  // sfix14_En5
  input   signed [13:0] k14;  // sfix14_En5
  input   signed [13:0] k15;  // sfix14_En5
  input   signed [13:0] k16;  // sfix14_En5
  input   signed [13:0] w1;  // sfix14_En5
  input   signed [13:0] w2;  // sfix14_En5
  input   signed [13:0] w3;  // sfix14_En5
  input   signed [13:0] w4;  // sfix14_En5
  input   signed [13:0] w5;  // sfix14_En5
  input   signed [13:0] w6;  // sfix14_En5
  input   signed [13:0] w7;  // sfix14_En5
  input   signed [13:0] w8;  // sfix14_En5
  input   signed [13:0] w9;  // sfix14_En5
  output  signed [13:0] R1;  // sfix14_E3
  output  signed [13:0] R2;  // sfix14_E3
  output  signed [13:0] R3;  // sfix14_E3
  output  signed [13:0] R4;  // sfix14_E3


  wire signed [13:0] winograd_d_fixpt_g_1_2;  // sfix14_En4
  wire signed [13:0] winograd_d_fixpt_g_2_2;  // sfix14_En4
  wire signed [13:0] winograd_d_fixpt_g_3_2;  // sfix14_En4
  wire signed [13:0] winograd_d_fixpt_g_1_3;  // sfix14_En4
  wire signed [13:0] winograd_d_fixpt_g_2_3;  // sfix14_En4
  wire signed [13:0] winograd_d_fixpt_g_3_3;  // sfix14_En4
  wire signed [14:0] winograd_d_fixpt_c;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_c_1;  // sfix15_En5
  wire signed [13:0] winograd_d_fixpt_m2;  // sfix14_E3
  wire signed [13:0] winograd_d_fixpt_m3;  // sfix14_E3
  wire signed [13:0] winograd_d_fixpt_m2_1;  // sfix14_E3
  wire signed [14:0] winograd_d_fixpt_c_2;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_c_3;  // sfix15_En5
  wire signed [13:0] winograd_d_fixpt_m2_2;  // sfix14_E3
  wire signed [13:0] winograd_d_fixpt_m3_1;  // sfix14_E3
  wire signed [13:0] winograd_d_fixpt_m1_2;  // sfix14_E3
  wire signed [14:0] winograd_d_fixpt_c_4;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_c_5;  // sfix15_En5
  wire signed [13:0] winograd_d_fixpt_m2_3;  // sfix14_E3
  wire signed [13:0] winograd_d_fixpt_m3_2;  // sfix14_E3
  wire signed [13:0] winograd_d_fixpt_m1_3;  // sfix14_E3
  wire signed [13:0] winograd_d_fixpt_m2_3_1;  // sfix14_E3
  wire signed [14:0] winograd_d_fixpt_c_6;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_c_7;  // sfix15_En5
  wire signed [13:0] winograd_d_fixpt_m2_4;  // sfix14_E3
  wire signed [13:0] winograd_d_fixpt_m3_3;  // sfix14_E3
  wire signed [14:0] winograd_d_fixpt_add_cast;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_add_cast_1;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_add_temp;  // sfix15_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_2;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_3;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_temp_1;  // sfix16_En5
  wire signed [16:0] winograd_d_fixpt_cast;  // sfix17_En6
  wire signed [16:0] winograd_d_fixpt_cast_1;  // sfix17_En6
  wire signed [14:0] winograd_d_fixpt_add_cast_4;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_add_cast_5;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_add_temp_2;  // sfix15_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_6;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_7;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_temp_3;  // sfix16_En5
  wire signed [16:0] winograd_d_fixpt_cast_2;  // sfix17_En6
  wire signed [16:0] winograd_d_fixpt_cast_3;  // sfix17_En6
  wire signed [14:0] winograd_d_fixpt_add_cast_8;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_add_cast_9;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_add_temp_4;  // sfix15_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_10;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_11;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_temp_5;  // sfix16_En5
  wire signed [16:0] winograd_d_fixpt_cast_4;  // sfix17_En6
  wire signed [16:0] winograd_d_fixpt_cast_5;  // sfix17_En6
  wire signed [14:0] winograd_d_fixpt_sub_cast;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_cast_1;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_temp;  // sfix15_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_12;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_13;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_temp_6;  // sfix16_En5
  wire signed [16:0] winograd_d_fixpt_cast_6;  // sfix17_En6
  wire signed [16:0] winograd_d_fixpt_cast_7;  // sfix17_En6
  wire signed [14:0] winograd_d_fixpt_sub_cast_2;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_cast_3;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_temp_1;  // sfix15_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_14;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_15;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_temp_7;  // sfix16_En5
  wire signed [16:0] winograd_d_fixpt_cast_8;  // sfix17_En6
  wire signed [16:0] winograd_d_fixpt_cast_9;  // sfix17_En6
  wire signed [14:0] winograd_d_fixpt_sub_cast_4;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_cast_5;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_temp_2;  // sfix15_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_16;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_17;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_temp_8;  // sfix16_En5
  wire signed [16:0] winograd_d_fixpt_cast_10;  // sfix17_En6
  wire signed [16:0] winograd_d_fixpt_cast_11;  // sfix17_En6
  wire signed [14:0] winograd_d_fixpt_sub_cast_6;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_cast_7;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_cast_8;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_cast_9;  // sfix15_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_18;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_19;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_temp_9;  // sfix16_En5
  wire signed [14:0] winograd_d_fixpt_add_cast_20;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_add_cast_21;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_add_temp_10;  // sfix15_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_22;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_23;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_temp_11;  // sfix16_En5
  wire signed [16:0] winograd_d_fixpt_cast_12;  // sfix17_En6
  wire signed [16:0] winograd_d_fixpt_cast_13;  // sfix17_En6
  wire signed [13:0] winograd_d_fixpt_cast_14;  // sfix14_En3
  wire signed [29:0] winograd_d_fixpt_mul_temp;  // sfix30_En8
  wire signed [15:0] winograd_d_fixpt_sub_cast_10;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_sub_cast_11;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_sub_temp_3;  // sfix16_En5
  wire signed [14:0] winograd_d_fixpt_sub_cast_12;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_cast_13;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_temp_4;  // sfix15_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_24;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_25;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_temp_12;  // sfix16_En5
  wire signed [16:0] winograd_d_fixpt_cast_15;  // sfix17_En6
  wire signed [16:0] winograd_d_fixpt_cast_16;  // sfix17_En6
  wire signed [13:0] winograd_d_fixpt_cast_17;  // sfix14_En3
  wire signed [29:0] winograd_d_fixpt_mul_temp_1;  // sfix30_En8
  wire signed [14:0] winograd_d_fixpt_sub_cast_14;  // sfix15_E3
  wire signed [14:0] winograd_d_fixpt_sub_cast_15;  // sfix15_E3
  wire signed [14:0] winograd_d_fixpt_sub_temp_5;  // sfix15_E3
  wire signed [15:0] winograd_d_fixpt_sub_cast_16;  // sfix16_E3
  wire signed [15:0] winograd_d_fixpt_sub_cast_17;  // sfix16_En5
  wire signed [14:0] winograd_d_fixpt_sub_cast_18;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_cast_19;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_temp_6;  // sfix15_En5
  wire signed [15:0] winograd_d_fixpt_sub_cast_20;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_sub_temp_7;  // sfix16_En5
  wire signed [13:0] winograd_d_fixpt_cast_18;  // sfix14_En4
  wire signed [29:0] winograd_d_fixpt_mul_temp_2;  // sfix30_En9
  wire signed [13:0] winograd_d_fixpt_sub_cast_21;  // sfix14_E3
  wire signed [15:0] winograd_d_fixpt_sub_cast_22;  // sfix16_E3
  wire signed [15:0] winograd_d_fixpt_sub_temp_8;  // sfix16_E3
  wire signed [14:0] winograd_d_fixpt_add_cast_26;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_add_cast_27;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_add_cast_28;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_add_cast_29;  // sfix15_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_30;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_31;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_temp_13;  // sfix16_En5
  wire signed [14:0] winograd_d_fixpt_add_cast_32;  // sfix15_En4
  wire signed [14:0] winograd_d_fixpt_add_cast_33;  // sfix15_En4
  wire signed [14:0] winograd_d_fixpt_add_temp_14;  // sfix15_En4
  wire signed [15:0] winograd_d_fixpt_add_cast_34;  // sfix16_En4
  wire signed [15:0] winograd_d_fixpt_add_cast_35;  // sfix16_En4
  wire signed [15:0] winograd_d_fixpt_add_temp_15;  // sfix16_En4
  wire signed [16:0] winograd_d_fixpt_cast_19;  // sfix17_En5
  wire signed [16:0] winograd_d_fixpt_cast_20;  // sfix17_En5
  wire signed [13:0] winograd_d_fixpt_cast_21;  // sfix14_En3
  wire signed [29:0] winograd_d_fixpt_mul_temp_3;  // sfix30_En8
  wire signed [15:0] winograd_d_fixpt_sub_cast_23;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_sub_cast_24;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_sub_temp_9;  // sfix16_En5
  wire signed [14:0] winograd_d_fixpt_sub_cast_25;  // sfix15_En4
  wire signed [14:0] winograd_d_fixpt_sub_cast_26;  // sfix15_En4
  wire signed [14:0] winograd_d_fixpt_sub_temp_10;  // sfix15_En4
  wire signed [15:0] winograd_d_fixpt_add_cast_36;  // sfix16_En4
  wire signed [15:0] winograd_d_fixpt_add_cast_37;  // sfix16_En4
  wire signed [15:0] winograd_d_fixpt_add_temp_16;  // sfix16_En4
  wire signed [16:0] winograd_d_fixpt_cast_22;  // sfix17_En5
  wire signed [16:0] winograd_d_fixpt_cast_23;  // sfix17_En5
  wire signed [13:0] winograd_d_fixpt_cast_24;  // sfix14_En3
  wire signed [29:0] winograd_d_fixpt_mul_temp_4;  // sfix30_En8
  wire signed [14:0] winograd_d_fixpt_add_cast_38;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_add_cast_39;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_add_temp_17;  // sfix15_En5
  wire signed [15:0] winograd_d_fixpt_sub_cast_27;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_sub_cast_28;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_sub_temp_11;  // sfix16_En5
  wire signed [29:0] winograd_d_fixpt_mul_temp_5;  // sfix30_En9
  wire signed [13:0] winograd_d_fixpt_add_cast_40;  // sfix14_E3
  wire signed [14:0] winograd_d_fixpt_add_cast_41;  // sfix15_E3
  wire signed [14:0] winograd_d_fixpt_add_cast_42;  // sfix15_E3
  wire signed [14:0] winograd_d_fixpt_add_temp_18;  // sfix15_E3
  wire signed [15:0] winograd_d_fixpt_add_cast_43;  // sfix16_E3
  wire signed [15:0] winograd_d_fixpt_add_cast_44;  // sfix16_E3
  wire signed [15:0] winograd_d_fixpt_add_temp_19;  // sfix16_E3
  wire signed [14:0] winograd_d_fixpt_sub_cast_29;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_cast_30;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_cast_31;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_cast_32;  // sfix15_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_45;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_46;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_temp_20;  // sfix16_En5
  wire signed [14:0] winograd_d_fixpt_add_cast_47;  // sfix15_En4
  wire signed [14:0] winograd_d_fixpt_add_cast_48;  // sfix15_En4
  wire signed [14:0] winograd_d_fixpt_add_temp_21;  // sfix15_En4
  wire signed [15:0] winograd_d_fixpt_add_cast_49;  // sfix16_En4
  wire signed [15:0] winograd_d_fixpt_add_cast_50;  // sfix16_En4
  wire signed [15:0] winograd_d_fixpt_add_temp_22;  // sfix16_En4
  wire signed [16:0] winograd_d_fixpt_cast_25;  // sfix17_En5
  wire signed [16:0] winograd_d_fixpt_cast_26;  // sfix17_En5
  wire signed [13:0] winograd_d_fixpt_cast_27;  // sfix14_En3
  wire signed [29:0] winograd_d_fixpt_mul_temp_6;  // sfix30_En8
  wire signed [15:0] winograd_d_fixpt_sub_cast_33;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_sub_cast_34;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_sub_temp_12;  // sfix16_En5
  wire signed [14:0] winograd_d_fixpt_sub_cast_35;  // sfix15_En4
  wire signed [14:0] winograd_d_fixpt_sub_cast_36;  // sfix15_En4
  wire signed [14:0] winograd_d_fixpt_sub_temp_13;  // sfix15_En4
  wire signed [15:0] winograd_d_fixpt_add_cast_51;  // sfix16_En4
  wire signed [15:0] winograd_d_fixpt_add_cast_52;  // sfix16_En4
  wire signed [15:0] winograd_d_fixpt_add_temp_23;  // sfix16_En4
  wire signed [16:0] winograd_d_fixpt_cast_28;  // sfix17_En5
  wire signed [16:0] winograd_d_fixpt_cast_29;  // sfix17_En5
  wire signed [13:0] winograd_d_fixpt_cast_30;  // sfix14_En3
  wire signed [29:0] winograd_d_fixpt_mul_temp_7;  // sfix30_En8
  wire signed [14:0] winograd_d_fixpt_sub_cast_37;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_cast_38;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_temp_14;  // sfix15_En5
  wire signed [15:0] winograd_d_fixpt_sub_cast_39;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_sub_cast_40;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_sub_temp_15;  // sfix16_En5
  wire signed [29:0] winograd_d_fixpt_mul_temp_8;  // sfix30_En9
  wire signed [13:0] winograd_d_fixpt_add_cast_53;  // sfix14_E3
  wire signed [14:0] winograd_d_fixpt_add_cast_54;  // sfix15_E3
  wire signed [14:0] winograd_d_fixpt_add_cast_55;  // sfix15_E3
  wire signed [14:0] winograd_d_fixpt_add_temp_24;  // sfix15_E3
  wire signed [15:0] winograd_d_fixpt_add_cast_56;  // sfix16_E3
  wire signed [15:0] winograd_d_fixpt_add_cast_57;  // sfix16_E3
  wire signed [15:0] winograd_d_fixpt_add_temp_25;  // sfix16_E3
  wire signed [14:0] winograd_d_fixpt_sub_cast_41;  // sfix15_E3
  wire signed [14:0] winograd_d_fixpt_sub_cast_42;  // sfix15_E3
  wire signed [14:0] winograd_d_fixpt_sub_temp_16;  // sfix15_E3
  wire signed [15:0] winograd_d_fixpt_sub_cast_43;  // sfix16_E3
  wire signed [15:0] winograd_d_fixpt_sub_cast_44;  // sfix16_En5
  wire signed [14:0] winograd_d_fixpt_sub_cast_45;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_cast_46;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_temp_17;  // sfix15_En5
  wire signed [15:0] winograd_d_fixpt_sub_cast_47;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_sub_temp_18;  // sfix16_En5
  wire signed [29:0] winograd_d_fixpt_mul_temp_9;  // sfix30_En9
  wire signed [13:0] winograd_d_fixpt_sub_cast_48;  // sfix14_E3
  wire signed [15:0] winograd_d_fixpt_sub_cast_49;  // sfix16_E3
  wire signed [15:0] winograd_d_fixpt_sub_temp_19;  // sfix16_E3
  wire signed [14:0] winograd_d_fixpt_sub_cast_50;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_cast_51;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_cast_52;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_cast_53;  // sfix15_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_58;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_59;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_temp_26;  // sfix16_En5
  wire signed [14:0] winograd_d_fixpt_add_cast_60;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_add_cast_61;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_add_temp_27;  // sfix15_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_62;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_63;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_temp_28;  // sfix16_En5
  wire signed [16:0] winograd_d_fixpt_cast_31;  // sfix17_En6
  wire signed [16:0] winograd_d_fixpt_cast_32;  // sfix17_En6
  wire signed [13:0] winograd_d_fixpt_cast_33;  // sfix14_En3
  wire signed [29:0] winograd_d_fixpt_mul_temp_10;  // sfix30_En8
  wire signed [15:0] winograd_d_fixpt_sub_cast_54;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_sub_cast_55;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_sub_temp_20;  // sfix16_En5
  wire signed [14:0] winograd_d_fixpt_sub_cast_56;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_cast_57;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_temp_21;  // sfix15_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_64;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_cast_65;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_add_temp_29;  // sfix16_En5
  wire signed [16:0] winograd_d_fixpt_cast_34;  // sfix17_En6
  wire signed [16:0] winograd_d_fixpt_cast_35;  // sfix17_En6
  wire signed [13:0] winograd_d_fixpt_cast_36;  // sfix14_En3
  wire signed [29:0] winograd_d_fixpt_mul_temp_11;  // sfix30_En8
  wire signed [14:0] winograd_d_fixpt_sub_cast_58;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_cast_59;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_temp_22;  // sfix15_En5
  wire signed [15:0] winograd_d_fixpt_sub_cast_60;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_sub_cast_61;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_sub_temp_23;  // sfix16_En5
  wire signed [13:0] winograd_d_fixpt_cast_37;  // sfix14_En4
  wire signed [29:0] winograd_d_fixpt_mul_temp_12;  // sfix30_En9
  wire signed [13:0] winograd_d_fixpt_add_cast_66;  // sfix14_E3
  wire signed [14:0] winograd_d_fixpt_add_cast_67;  // sfix15_E3
  wire signed [14:0] winograd_d_fixpt_add_cast_68;  // sfix15_E3
  wire signed [14:0] winograd_d_fixpt_add_temp_30;  // sfix15_E3
  wire signed [15:0] winograd_d_fixpt_add_cast_69;  // sfix16_E3
  wire signed [15:0] winograd_d_fixpt_add_cast_70;  // sfix16_E3
  wire signed [15:0] winograd_d_fixpt_add_temp_31;  // sfix16_E3
  wire signed [13:0] winograd_d_fixpt_add_cast_71;  // sfix14_E3
  wire signed [14:0] winograd_d_fixpt_add_cast_72;  // sfix15_E3
  wire signed [14:0] winograd_d_fixpt_add_cast_73;  // sfix15_E3
  wire signed [14:0] winograd_d_fixpt_add_temp_32;  // sfix15_E3
  wire signed [15:0] winograd_d_fixpt_add_cast_74;  // sfix16_E3
  wire signed [15:0] winograd_d_fixpt_add_cast_75;  // sfix16_E3
  wire signed [15:0] winograd_d_fixpt_add_temp_33;  // sfix16_E3
  wire signed [14:0] winograd_d_fixpt_add_cast_76;  // sfix15_E3
  wire signed [14:0] winograd_d_fixpt_sub_cast_62;  // sfix15_E3
  wire signed [14:0] winograd_d_fixpt_sub_cast_63;  // sfix15_E3
  wire signed [14:0] winograd_d_fixpt_sub_temp_24;  // sfix15_E3
  wire signed [15:0] winograd_d_fixpt_sub_cast_64;  // sfix16_E3
  wire signed [15:0] winograd_d_fixpt_sub_cast_65;  // sfix16_En5
  wire signed [14:0] winograd_d_fixpt_add_cast_77;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_add_cast_78;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_add_temp_34;  // sfix15_En5
  wire signed [15:0] winograd_d_fixpt_sub_cast_66;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_sub_temp_25;  // sfix16_En5
  wire signed [29:0] winograd_d_fixpt_mul_temp_13;  // sfix30_En9
  wire signed [13:0] winograd_d_fixpt_sub_cast_67;  // sfix14_E3
  wire signed [15:0] winograd_d_fixpt_sub_cast_68;  // sfix16_E3
  wire signed [15:0] winograd_d_fixpt_sub_temp_26;  // sfix16_E3
  wire signed [13:0] winograd_d_fixpt_add_cast_79;  // sfix14_E3
  wire signed [14:0] winograd_d_fixpt_add_cast_80;  // sfix15_E3
  wire signed [14:0] winograd_d_fixpt_add_temp_35;  // sfix15_E3
  wire signed [15:0] winograd_d_fixpt_add_cast_81;  // sfix16_E3
  wire signed [15:0] winograd_d_fixpt_add_cast_82;  // sfix16_E3
  wire signed [15:0] winograd_d_fixpt_add_temp_36;  // sfix16_E3
  wire signed [14:0] winograd_d_fixpt_sub_cast_69;  // sfix15_E3
  wire signed [14:0] winograd_d_fixpt_sub_cast_70;  // sfix15_E3
  wire signed [14:0] winograd_d_fixpt_sub_temp_27;  // sfix15_E3
  wire signed [15:0] winograd_d_fixpt_sub_cast_71;  // sfix16_E3
  wire signed [14:0] winograd_d_fixpt_sub_cast_72;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_cast_73;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_temp_28;  // sfix15_En5
  wire signed [15:0] winograd_d_fixpt_sub_cast_74;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_sub_cast_75;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_sub_temp_29;  // sfix16_En5
  wire signed [13:0] winograd_d_fixpt_cast_38;  // sfix14_En4
  wire signed [29:0] winograd_d_fixpt_mul_temp_14;  // sfix30_En9
  wire signed [13:0] winograd_d_fixpt_add_cast_83;  // sfix14_E3
  wire signed [14:0] winograd_d_fixpt_add_cast_84;  // sfix15_E3
  wire signed [14:0] winograd_d_fixpt_add_cast_85;  // sfix15_E3
  wire signed [14:0] winograd_d_fixpt_add_temp_37;  // sfix15_E3
  wire signed [15:0] winograd_d_fixpt_add_cast_86;  // sfix16_E3
  wire signed [15:0] winograd_d_fixpt_add_cast_87;  // sfix16_E3
  wire signed [15:0] winograd_d_fixpt_add_temp_38;  // sfix16_E3
  wire signed [13:0] winograd_d_fixpt_sub_cast_76;  // sfix14_E3
  wire signed [15:0] winograd_d_fixpt_sub_cast_77;  // sfix16_E3
  wire signed [15:0] winograd_d_fixpt_sub_temp_30;  // sfix16_E3
  wire signed [14:0] winograd_d_fixpt_sub_cast_78;  // sfix15_E3
  wire signed [14:0] winograd_d_fixpt_sub_cast_79;  // sfix15_E3
  wire signed [14:0] winograd_d_fixpt_sub_temp_31;  // sfix15_E3
  wire signed [15:0] winograd_d_fixpt_sub_cast_80;  // sfix16_E3
  wire signed [14:0] winograd_d_fixpt_sub_cast_81;  // sfix15_E3
  wire signed [14:0] winograd_d_fixpt_sub_cast_82;  // sfix15_E3
  wire signed [14:0] winograd_d_fixpt_sub_temp_32;  // sfix15_E3
  wire signed [15:0] winograd_d_fixpt_sub_cast_83;  // sfix16_E3
  wire signed [15:0] winograd_d_fixpt_sub_cast_84;  // sfix16_En5
  wire signed [14:0] winograd_d_fixpt_sub_cast_85;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_cast_86;  // sfix15_En5
  wire signed [14:0] winograd_d_fixpt_sub_temp_33;  // sfix15_En5
  wire signed [15:0] winograd_d_fixpt_sub_cast_87;  // sfix16_En5
  wire signed [15:0] winograd_d_fixpt_sub_temp_34;  // sfix16_En5
  wire signed [13:0] winograd_d_fixpt_cast_39;  // sfix14_En4
  wire signed [29:0] winograd_d_fixpt_mul_temp_15;  // sfix30_En9
  wire signed [13:0] winograd_d_fixpt_sub_cast_88;  // sfix14_E3
  wire signed [15:0] winograd_d_fixpt_sub_cast_89;  // sfix16_E3
  wire signed [15:0] winograd_d_fixpt_sub_temp_35;  // sfix16_E3
  wire signed [13:0] winograd_d_fixpt_sub_cast_90;  // sfix14_E3
  wire signed [15:0] winograd_d_fixpt_sub_cast_91;  // sfix16_E3
  wire signed [15:0] winograd_d_fixpt_sub_temp_36;  // sfix16_E3


  //HDL code generation from MATLAB function: winograd_d_fixpt
  //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  //                                                                          %
  //           Generated by MATLAB 9.6 and Fixed-Point Designer 6.3           %
  //                                                                          %
  //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  //[R1,R2,R3,R4]=winograd_d(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,1,2,3,4,5,6,7,8,9)
  // R=zeros(1,4);
  //R=winograd_d([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],[1,2,3,4,5,6,7,8,9])
  // d=zeros(4,4);
  // g=zeros(3,3);
  // g_=zeros(3,4);
  // m=zeros(2,4);
  // 
  // R=int16(R);
  // d=int16(d);
  // g=int16(g);
  // g_=int16(g_);
  // m=int16(m);
  // 
  // d(:,1)=Ki(1:4);
  // d(:,2)=Ki(5:8);
  // d(:,3)=Ki(9:12);
  // d(:,4)=Ki(13:16);
  // 
  // g(:,1)=Wi(1:3);
  // g(:,2)=Wi(4:6);
  // g(:,3)=Wi(7:9);
  // 
  // g_(:,1)=g(:,1);
  // g_(:,2)=(g(:,1)+g(:,2)+g(:,3))/2;
  // g_(:,3)=(g(:,1)-g(:,2)+g(:,3))/2;
  // g_(:,4)=g(:,3);
  // 
  //     m(:,1)=winograd_s((d(:,1)-d(:,3)),g_(:,1));
  //     m(:,2)=winograd_s((d(:,2)+d(:,3)),g_(:,2));
  //     m(:,3)=winograd_s((d(:,3)-d(:,2)),g_(:,3));
  //     m(:,4)=winograd_s((d(:,2)-d(:,4)),g_(:,4));
  //     R(1:2)=m(:,1)+m(:,2)+m(:,3);
  //     R(3:4)=m(:,2)-m(:,3)-m(:,4);
  assign winograd_d_fixpt_add_cast = {w1[13], w1};
  assign winograd_d_fixpt_add_cast_1 = {w4[13], w4};
  assign winograd_d_fixpt_add_temp = winograd_d_fixpt_add_cast + winograd_d_fixpt_add_cast_1;
  assign winograd_d_fixpt_add_cast_2 = {winograd_d_fixpt_add_temp[14], winograd_d_fixpt_add_temp};
  assign winograd_d_fixpt_add_cast_3 = {{2{w7[13]}}, w7};
  assign winograd_d_fixpt_add_temp_1 = winograd_d_fixpt_add_cast_2 + winograd_d_fixpt_add_cast_3;
  assign winograd_d_fixpt_cast = {winograd_d_fixpt_add_temp_1, 1'b0};
  assign winograd_d_fixpt_cast_1 = winograd_d_fixpt_cast >>> 8'd1;
  assign winograd_d_fixpt_g_1_2 = winograd_d_fixpt_cast_1[15:2];
  assign winograd_d_fixpt_add_cast_4 = {w2[13], w2};
  assign winograd_d_fixpt_add_cast_5 = {w5[13], w5};
  assign winograd_d_fixpt_add_temp_2 = winograd_d_fixpt_add_cast_4 + winograd_d_fixpt_add_cast_5;
  assign winograd_d_fixpt_add_cast_6 = {winograd_d_fixpt_add_temp_2[14], winograd_d_fixpt_add_temp_2};
  assign winograd_d_fixpt_add_cast_7 = {{2{w8[13]}}, w8};
  assign winograd_d_fixpt_add_temp_3 = winograd_d_fixpt_add_cast_6 + winograd_d_fixpt_add_cast_7;
  assign winograd_d_fixpt_cast_2 = {winograd_d_fixpt_add_temp_3, 1'b0};
  assign winograd_d_fixpt_cast_3 = winograd_d_fixpt_cast_2 >>> 8'd1;
  assign winograd_d_fixpt_g_2_2 = winograd_d_fixpt_cast_3[15:2];
  assign winograd_d_fixpt_add_cast_8 = {w3[13], w3};
  assign winograd_d_fixpt_add_cast_9 = {w6[13], w6};
  assign winograd_d_fixpt_add_temp_4 = winograd_d_fixpt_add_cast_8 + winograd_d_fixpt_add_cast_9;
  assign winograd_d_fixpt_add_cast_10 = {winograd_d_fixpt_add_temp_4[14], winograd_d_fixpt_add_temp_4};
  assign winograd_d_fixpt_add_cast_11 = {{2{w9[13]}}, w9};
  assign winograd_d_fixpt_add_temp_5 = winograd_d_fixpt_add_cast_10 + winograd_d_fixpt_add_cast_11;
  assign winograd_d_fixpt_cast_4 = {winograd_d_fixpt_add_temp_5, 1'b0};
  assign winograd_d_fixpt_cast_5 = winograd_d_fixpt_cast_4 >>> 8'd1;
  assign winograd_d_fixpt_g_3_2 = winograd_d_fixpt_cast_5[15:2];
  assign winograd_d_fixpt_sub_cast = {w1[13], w1};
  assign winograd_d_fixpt_sub_cast_1 = {w4[13], w4};
  assign winograd_d_fixpt_sub_temp = winograd_d_fixpt_sub_cast - winograd_d_fixpt_sub_cast_1;
  assign winograd_d_fixpt_add_cast_12 = {winograd_d_fixpt_sub_temp[14], winograd_d_fixpt_sub_temp};
  assign winograd_d_fixpt_add_cast_13 = {{2{w7[13]}}, w7};
  assign winograd_d_fixpt_add_temp_6 = winograd_d_fixpt_add_cast_12 + winograd_d_fixpt_add_cast_13;
  assign winograd_d_fixpt_cast_6 = {winograd_d_fixpt_add_temp_6, 1'b0};
  assign winograd_d_fixpt_cast_7 = winograd_d_fixpt_cast_6 >>> 8'd1;
  assign winograd_d_fixpt_g_1_3 = winograd_d_fixpt_cast_7[15:2];
  assign winograd_d_fixpt_sub_cast_2 = {w2[13], w2};
  assign winograd_d_fixpt_sub_cast_3 = {w5[13], w5};
  assign winograd_d_fixpt_sub_temp_1 = winograd_d_fixpt_sub_cast_2 - winograd_d_fixpt_sub_cast_3;
  assign winograd_d_fixpt_add_cast_14 = {winograd_d_fixpt_sub_temp_1[14], winograd_d_fixpt_sub_temp_1};
  assign winograd_d_fixpt_add_cast_15 = {{2{w8[13]}}, w8};
  assign winograd_d_fixpt_add_temp_7 = winograd_d_fixpt_add_cast_14 + winograd_d_fixpt_add_cast_15;
  assign winograd_d_fixpt_cast_8 = {winograd_d_fixpt_add_temp_7, 1'b0};
  assign winograd_d_fixpt_cast_9 = winograd_d_fixpt_cast_8 >>> 8'd1;
  assign winograd_d_fixpt_g_2_3 = winograd_d_fixpt_cast_9[15:2];
  assign winograd_d_fixpt_sub_cast_4 = {w3[13], w3};
  assign winograd_d_fixpt_sub_cast_5 = {w6[13], w6};
  assign winograd_d_fixpt_sub_temp_2 = winograd_d_fixpt_sub_cast_4 - winograd_d_fixpt_sub_cast_5;
  assign winograd_d_fixpt_add_cast_16 = {winograd_d_fixpt_sub_temp_2[14], winograd_d_fixpt_sub_temp_2};
  assign winograd_d_fixpt_add_cast_17 = {{2{w9[13]}}, w9};
  assign winograd_d_fixpt_add_temp_8 = winograd_d_fixpt_add_cast_16 + winograd_d_fixpt_add_cast_17;
  assign winograd_d_fixpt_cast_10 = {winograd_d_fixpt_add_temp_8, 1'b0};
  assign winograd_d_fixpt_cast_11 = winograd_d_fixpt_cast_10 >>> 8'd1;
  assign winograd_d_fixpt_g_3_3 = winograd_d_fixpt_cast_11[15:2];
  assign winograd_d_fixpt_sub_cast_6 = {k2[13], k2};
  assign winograd_d_fixpt_sub_cast_7 = {k10[13], k10};
  assign winograd_d_fixpt_c = winograd_d_fixpt_sub_cast_6 - winograd_d_fixpt_sub_cast_7;
  assign winograd_d_fixpt_sub_cast_8 = {k3[13], k3};
  assign winograd_d_fixpt_sub_cast_9 = {k11[13], k11};
  assign winograd_d_fixpt_c_1 = winograd_d_fixpt_sub_cast_8 - winograd_d_fixpt_sub_cast_9;
  // r=winograd_s([1,2,3,4],[1,2,3])
  // g_=zeros(1,4);
  // m=zeros(1,4);
  // r=zeros(1,2);
  // 
  // r=int16(r);
  // m=int16(m);
  // g_=int16(g_);
  // 
  // g_(1)=g(1);
  // g_(2)=(g(1)+g(2)+g(3))/2;
  // g_(3)=(g(1)-g(2)+g(3))/2;
  // g_(4)=g(3);
  // 
  // 
  //     m(1)=(d(1)-d(3))*g_(1);
  //     m(2)=(d(2)+d(3))*g_(2);
  //     m(3)=(d(3)-d(2))*g_(3);
  //     m(4)=(d(2)-d(4))*g_(4);
  //     r(1)=m(1)+m(2)+m(3);
  //     r(2)=m(2)-m(3)-m(4);
  assign winograd_d_fixpt_add_cast_18 = {winograd_d_fixpt_c[14], winograd_d_fixpt_c};
  assign winograd_d_fixpt_add_cast_19 = {winograd_d_fixpt_c_1[14], winograd_d_fixpt_c_1};
  assign winograd_d_fixpt_add_temp_9 = winograd_d_fixpt_add_cast_18 + winograd_d_fixpt_add_cast_19;
  assign winograd_d_fixpt_add_cast_20 = {w1[13], w1};
  assign winograd_d_fixpt_add_cast_21 = {w2[13], w2};
  assign winograd_d_fixpt_add_temp_10 = winograd_d_fixpt_add_cast_20 + winograd_d_fixpt_add_cast_21;
  assign winograd_d_fixpt_add_cast_22 = {winograd_d_fixpt_add_temp_10[14], winograd_d_fixpt_add_temp_10};
  assign winograd_d_fixpt_add_cast_23 = {{2{w3[13]}}, w3};
  assign winograd_d_fixpt_add_temp_11 = winograd_d_fixpt_add_cast_22 + winograd_d_fixpt_add_cast_23;
  assign winograd_d_fixpt_cast_12 = {winograd_d_fixpt_add_temp_11, 1'b0};
  assign winograd_d_fixpt_cast_13 = winograd_d_fixpt_cast_12 >>> 8'd1;
  assign winograd_d_fixpt_cast_14 = winograd_d_fixpt_cast_13[16:3];
  assign winograd_d_fixpt_mul_temp = winograd_d_fixpt_add_temp_9 * winograd_d_fixpt_cast_14;
  assign winograd_d_fixpt_m2 = winograd_d_fixpt_mul_temp[24:11];
  assign winograd_d_fixpt_sub_cast_10 = {winograd_d_fixpt_c_1[14], winograd_d_fixpt_c_1};
  assign winograd_d_fixpt_sub_cast_11 = {winograd_d_fixpt_c[14], winograd_d_fixpt_c};
  assign winograd_d_fixpt_sub_temp_3 = winograd_d_fixpt_sub_cast_10 - winograd_d_fixpt_sub_cast_11;
  assign winograd_d_fixpt_sub_cast_12 = {w1[13], w1};
  assign winograd_d_fixpt_sub_cast_13 = {w2[13], w2};
  assign winograd_d_fixpt_sub_temp_4 = winograd_d_fixpt_sub_cast_12 - winograd_d_fixpt_sub_cast_13;
  assign winograd_d_fixpt_add_cast_24 = {winograd_d_fixpt_sub_temp_4[14], winograd_d_fixpt_sub_temp_4};
  assign winograd_d_fixpt_add_cast_25 = {{2{w3[13]}}, w3};
  assign winograd_d_fixpt_add_temp_12 = winograd_d_fixpt_add_cast_24 + winograd_d_fixpt_add_cast_25;
  assign winograd_d_fixpt_cast_15 = {winograd_d_fixpt_add_temp_12, 1'b0};
  assign winograd_d_fixpt_cast_16 = winograd_d_fixpt_cast_15 >>> 8'd1;
  assign winograd_d_fixpt_cast_17 = winograd_d_fixpt_cast_16[16:3];
  assign winograd_d_fixpt_mul_temp_1 = winograd_d_fixpt_sub_temp_3 * winograd_d_fixpt_cast_17;
  assign winograd_d_fixpt_m3 = winograd_d_fixpt_mul_temp_1[24:11];
  assign winograd_d_fixpt_sub_cast_14 = {winograd_d_fixpt_m2[13], winograd_d_fixpt_m2};
  assign winograd_d_fixpt_sub_cast_15 = {winograd_d_fixpt_m3[13], winograd_d_fixpt_m3};
  assign winograd_d_fixpt_sub_temp_5 = winograd_d_fixpt_sub_cast_14 - winograd_d_fixpt_sub_cast_15;
  assign winograd_d_fixpt_sub_cast_16 = {winograd_d_fixpt_sub_temp_5[14], winograd_d_fixpt_sub_temp_5};
  assign winograd_d_fixpt_sub_cast_17 = {winograd_d_fixpt_c[14], winograd_d_fixpt_c};
  assign winograd_d_fixpt_sub_cast_18 = {k4[13], k4};
  assign winograd_d_fixpt_sub_cast_19 = {k12[13], k12};
  assign winograd_d_fixpt_sub_temp_6 = winograd_d_fixpt_sub_cast_18 - winograd_d_fixpt_sub_cast_19;
  assign winograd_d_fixpt_sub_cast_20 = {winograd_d_fixpt_sub_temp_6[14], winograd_d_fixpt_sub_temp_6};
  assign winograd_d_fixpt_sub_temp_7 = winograd_d_fixpt_sub_cast_17 - winograd_d_fixpt_sub_cast_20;
  assign winograd_d_fixpt_cast_18 = {w3[13], w3[13:1]};
  assign winograd_d_fixpt_mul_temp_2 = winograd_d_fixpt_sub_temp_7 * winograd_d_fixpt_cast_18;
  assign winograd_d_fixpt_sub_cast_21 = winograd_d_fixpt_mul_temp_2[25:12];
  assign winograd_d_fixpt_sub_cast_22 = {{2{winograd_d_fixpt_sub_cast_21[13]}}, winograd_d_fixpt_sub_cast_21};
  assign winograd_d_fixpt_sub_temp_8 = winograd_d_fixpt_sub_cast_16 - winograd_d_fixpt_sub_cast_22;
  assign winograd_d_fixpt_m2_1 = winograd_d_fixpt_sub_temp_8[13:0];
  assign winograd_d_fixpt_add_cast_26 = {k6[13], k6};
  assign winograd_d_fixpt_add_cast_27 = {k10[13], k10};
  assign winograd_d_fixpt_c_2 = winograd_d_fixpt_add_cast_26 + winograd_d_fixpt_add_cast_27;
  assign winograd_d_fixpt_add_cast_28 = {k7[13], k7};
  assign winograd_d_fixpt_add_cast_29 = {k11[13], k11};
  assign winograd_d_fixpt_c_3 = winograd_d_fixpt_add_cast_28 + winograd_d_fixpt_add_cast_29;
  // r=winograd_s([1,2,3,4],[1,2,3])
  // g_=zeros(1,4);
  // m=zeros(1,4);
  // r=zeros(1,2);
  // 
  // r=int16(r);
  // m=int16(m);
  // g_=int16(g_);
  // 
  // g_(1)=g(1);
  // g_(2)=(g(1)+g(2)+g(3))/2;
  // g_(3)=(g(1)-g(2)+g(3))/2;
  // g_(4)=g(3);
  // 
  // 
  //     m(1)=(d(1)-d(3))*g_(1);
  //     m(2)=(d(2)+d(3))*g_(2);
  //     m(3)=(d(3)-d(2))*g_(3);
  //     m(4)=(d(2)-d(4))*g_(4);
  //     r(1)=m(1)+m(2)+m(3);
  //     r(2)=m(2)-m(3)-m(4);
  assign winograd_d_fixpt_add_cast_30 = {winograd_d_fixpt_c_2[14], winograd_d_fixpt_c_2};
  assign winograd_d_fixpt_add_cast_31 = {winograd_d_fixpt_c_3[14], winograd_d_fixpt_c_3};
  assign winograd_d_fixpt_add_temp_13 = winograd_d_fixpt_add_cast_30 + winograd_d_fixpt_add_cast_31;
  assign winograd_d_fixpt_add_cast_32 = {winograd_d_fixpt_g_1_2[13], winograd_d_fixpt_g_1_2};
  assign winograd_d_fixpt_add_cast_33 = {winograd_d_fixpt_g_2_2[13], winograd_d_fixpt_g_2_2};
  assign winograd_d_fixpt_add_temp_14 = winograd_d_fixpt_add_cast_32 + winograd_d_fixpt_add_cast_33;
  assign winograd_d_fixpt_add_cast_34 = {winograd_d_fixpt_add_temp_14[14], winograd_d_fixpt_add_temp_14};
  assign winograd_d_fixpt_add_cast_35 = {{2{winograd_d_fixpt_g_3_2[13]}}, winograd_d_fixpt_g_3_2};
  assign winograd_d_fixpt_add_temp_15 = winograd_d_fixpt_add_cast_34 + winograd_d_fixpt_add_cast_35;
  assign winograd_d_fixpt_cast_19 = {winograd_d_fixpt_add_temp_15, 1'b0};
  assign winograd_d_fixpt_cast_20 = winograd_d_fixpt_cast_19 >>> 8'd1;
  assign winograd_d_fixpt_cast_21 = winograd_d_fixpt_cast_20[15:2];
  assign winograd_d_fixpt_mul_temp_3 = winograd_d_fixpt_add_temp_13 * winograd_d_fixpt_cast_21;
  assign winograd_d_fixpt_m2_2 = winograd_d_fixpt_mul_temp_3[24:11];
  assign winograd_d_fixpt_sub_cast_23 = {winograd_d_fixpt_c_3[14], winograd_d_fixpt_c_3};
  assign winograd_d_fixpt_sub_cast_24 = {winograd_d_fixpt_c_2[14], winograd_d_fixpt_c_2};
  assign winograd_d_fixpt_sub_temp_9 = winograd_d_fixpt_sub_cast_23 - winograd_d_fixpt_sub_cast_24;
  assign winograd_d_fixpt_sub_cast_25 = {winograd_d_fixpt_g_1_2[13], winograd_d_fixpt_g_1_2};
  assign winograd_d_fixpt_sub_cast_26 = {winograd_d_fixpt_g_2_2[13], winograd_d_fixpt_g_2_2};
  assign winograd_d_fixpt_sub_temp_10 = winograd_d_fixpt_sub_cast_25 - winograd_d_fixpt_sub_cast_26;
  assign winograd_d_fixpt_add_cast_36 = {winograd_d_fixpt_sub_temp_10[14], winograd_d_fixpt_sub_temp_10};
  assign winograd_d_fixpt_add_cast_37 = {{2{winograd_d_fixpt_g_3_2[13]}}, winograd_d_fixpt_g_3_2};
  assign winograd_d_fixpt_add_temp_16 = winograd_d_fixpt_add_cast_36 + winograd_d_fixpt_add_cast_37;
  assign winograd_d_fixpt_cast_22 = {winograd_d_fixpt_add_temp_16, 1'b0};
  assign winograd_d_fixpt_cast_23 = winograd_d_fixpt_cast_22 >>> 8'd1;
  assign winograd_d_fixpt_cast_24 = winograd_d_fixpt_cast_23[15:2];
  assign winograd_d_fixpt_mul_temp_4 = winograd_d_fixpt_sub_temp_9 * winograd_d_fixpt_cast_24;
  assign winograd_d_fixpt_m3_1 = winograd_d_fixpt_mul_temp_4[24:11];
  assign winograd_d_fixpt_add_cast_38 = {k5[13], k5};
  assign winograd_d_fixpt_add_cast_39 = {k9[13], k9};
  assign winograd_d_fixpt_add_temp_17 = winograd_d_fixpt_add_cast_38 + winograd_d_fixpt_add_cast_39;
  assign winograd_d_fixpt_sub_cast_27 = {winograd_d_fixpt_add_temp_17[14], winograd_d_fixpt_add_temp_17};
  assign winograd_d_fixpt_sub_cast_28 = {winograd_d_fixpt_c_3[14], winograd_d_fixpt_c_3};
  assign winograd_d_fixpt_sub_temp_11 = winograd_d_fixpt_sub_cast_27 - winograd_d_fixpt_sub_cast_28;
  assign winograd_d_fixpt_mul_temp_5 = winograd_d_fixpt_sub_temp_11 * winograd_d_fixpt_g_1_2;
  assign winograd_d_fixpt_add_cast_40 = winograd_d_fixpt_mul_temp_5[25:12];
  assign winograd_d_fixpt_add_cast_41 = {winograd_d_fixpt_add_cast_40[13], winograd_d_fixpt_add_cast_40};
  assign winograd_d_fixpt_add_cast_42 = {winograd_d_fixpt_m2_2[13], winograd_d_fixpt_m2_2};
  assign winograd_d_fixpt_add_temp_18 = winograd_d_fixpt_add_cast_41 + winograd_d_fixpt_add_cast_42;
  assign winograd_d_fixpt_add_cast_43 = {winograd_d_fixpt_add_temp_18[14], winograd_d_fixpt_add_temp_18};
  assign winograd_d_fixpt_add_cast_44 = {{2{winograd_d_fixpt_m3_1[13]}}, winograd_d_fixpt_m3_1};
  assign winograd_d_fixpt_add_temp_19 = winograd_d_fixpt_add_cast_43 + winograd_d_fixpt_add_cast_44;
  assign winograd_d_fixpt_m1_2 = winograd_d_fixpt_add_temp_19[13:0];
  assign winograd_d_fixpt_sub_cast_29 = {k10[13], k10};
  assign winograd_d_fixpt_sub_cast_30 = {k6[13], k6};
  assign winograd_d_fixpt_c_4 = winograd_d_fixpt_sub_cast_29 - winograd_d_fixpt_sub_cast_30;
  assign winograd_d_fixpt_sub_cast_31 = {k11[13], k11};
  assign winograd_d_fixpt_sub_cast_32 = {k7[13], k7};
  assign winograd_d_fixpt_c_5 = winograd_d_fixpt_sub_cast_31 - winograd_d_fixpt_sub_cast_32;
  // r=winograd_s([1,2,3,4],[1,2,3])
  // g_=zeros(1,4);
  // m=zeros(1,4);
  // r=zeros(1,2);
  // 
  // r=int16(r);
  // m=int16(m);
  // g_=int16(g_);
  // 
  // g_(1)=g(1);
  // g_(2)=(g(1)+g(2)+g(3))/2;
  // g_(3)=(g(1)-g(2)+g(3))/2;
  // g_(4)=g(3);
  // 
  // 
  //     m(1)=(d(1)-d(3))*g_(1);
  //     m(2)=(d(2)+d(3))*g_(2);
  //     m(3)=(d(3)-d(2))*g_(3);
  //     m(4)=(d(2)-d(4))*g_(4);
  //     r(1)=m(1)+m(2)+m(3);
  //     r(2)=m(2)-m(3)-m(4);
  assign winograd_d_fixpt_add_cast_45 = {winograd_d_fixpt_c_4[14], winograd_d_fixpt_c_4};
  assign winograd_d_fixpt_add_cast_46 = {winograd_d_fixpt_c_5[14], winograd_d_fixpt_c_5};
  assign winograd_d_fixpt_add_temp_20 = winograd_d_fixpt_add_cast_45 + winograd_d_fixpt_add_cast_46;
  assign winograd_d_fixpt_add_cast_47 = {winograd_d_fixpt_g_1_3[13], winograd_d_fixpt_g_1_3};
  assign winograd_d_fixpt_add_cast_48 = {winograd_d_fixpt_g_2_3[13], winograd_d_fixpt_g_2_3};
  assign winograd_d_fixpt_add_temp_21 = winograd_d_fixpt_add_cast_47 + winograd_d_fixpt_add_cast_48;
  assign winograd_d_fixpt_add_cast_49 = {winograd_d_fixpt_add_temp_21[14], winograd_d_fixpt_add_temp_21};
  assign winograd_d_fixpt_add_cast_50 = {{2{winograd_d_fixpt_g_3_3[13]}}, winograd_d_fixpt_g_3_3};
  assign winograd_d_fixpt_add_temp_22 = winograd_d_fixpt_add_cast_49 + winograd_d_fixpt_add_cast_50;
  assign winograd_d_fixpt_cast_25 = {winograd_d_fixpt_add_temp_22, 1'b0};
  assign winograd_d_fixpt_cast_26 = winograd_d_fixpt_cast_25 >>> 8'd1;
  assign winograd_d_fixpt_cast_27 = winograd_d_fixpt_cast_26[15:2];
  assign winograd_d_fixpt_mul_temp_6 = winograd_d_fixpt_add_temp_20 * winograd_d_fixpt_cast_27;
  assign winograd_d_fixpt_m2_3 = winograd_d_fixpt_mul_temp_6[24:11];
  assign winograd_d_fixpt_sub_cast_33 = {winograd_d_fixpt_c_5[14], winograd_d_fixpt_c_5};
  assign winograd_d_fixpt_sub_cast_34 = {winograd_d_fixpt_c_4[14], winograd_d_fixpt_c_4};
  assign winograd_d_fixpt_sub_temp_12 = winograd_d_fixpt_sub_cast_33 - winograd_d_fixpt_sub_cast_34;
  assign winograd_d_fixpt_sub_cast_35 = {winograd_d_fixpt_g_1_3[13], winograd_d_fixpt_g_1_3};
  assign winograd_d_fixpt_sub_cast_36 = {winograd_d_fixpt_g_2_3[13], winograd_d_fixpt_g_2_3};
  assign winograd_d_fixpt_sub_temp_13 = winograd_d_fixpt_sub_cast_35 - winograd_d_fixpt_sub_cast_36;
  assign winograd_d_fixpt_add_cast_51 = {winograd_d_fixpt_sub_temp_13[14], winograd_d_fixpt_sub_temp_13};
  assign winograd_d_fixpt_add_cast_52 = {{2{winograd_d_fixpt_g_3_3[13]}}, winograd_d_fixpt_g_3_3};
  assign winograd_d_fixpt_add_temp_23 = winograd_d_fixpt_add_cast_51 + winograd_d_fixpt_add_cast_52;
  assign winograd_d_fixpt_cast_28 = {winograd_d_fixpt_add_temp_23, 1'b0};
  assign winograd_d_fixpt_cast_29 = winograd_d_fixpt_cast_28 >>> 8'd1;
  assign winograd_d_fixpt_cast_30 = winograd_d_fixpt_cast_29[15:2];
  assign winograd_d_fixpt_mul_temp_7 = winograd_d_fixpt_sub_temp_12 * winograd_d_fixpt_cast_30;
  assign winograd_d_fixpt_m3_2 = winograd_d_fixpt_mul_temp_7[24:11];
  assign winograd_d_fixpt_sub_cast_37 = {k9[13], k9};
  assign winograd_d_fixpt_sub_cast_38 = {k5[13], k5};
  assign winograd_d_fixpt_sub_temp_14 = winograd_d_fixpt_sub_cast_37 - winograd_d_fixpt_sub_cast_38;
  assign winograd_d_fixpt_sub_cast_39 = {winograd_d_fixpt_sub_temp_14[14], winograd_d_fixpt_sub_temp_14};
  assign winograd_d_fixpt_sub_cast_40 = {winograd_d_fixpt_c_5[14], winograd_d_fixpt_c_5};
  assign winograd_d_fixpt_sub_temp_15 = winograd_d_fixpt_sub_cast_39 - winograd_d_fixpt_sub_cast_40;
  assign winograd_d_fixpt_mul_temp_8 = winograd_d_fixpt_sub_temp_15 * winograd_d_fixpt_g_1_3;
  assign winograd_d_fixpt_add_cast_53 = winograd_d_fixpt_mul_temp_8[25:12];
  assign winograd_d_fixpt_add_cast_54 = {winograd_d_fixpt_add_cast_53[13], winograd_d_fixpt_add_cast_53};
  assign winograd_d_fixpt_add_cast_55 = {winograd_d_fixpt_m2_3[13], winograd_d_fixpt_m2_3};
  assign winograd_d_fixpt_add_temp_24 = winograd_d_fixpt_add_cast_54 + winograd_d_fixpt_add_cast_55;
  assign winograd_d_fixpt_add_cast_56 = {winograd_d_fixpt_add_temp_24[14], winograd_d_fixpt_add_temp_24};
  assign winograd_d_fixpt_add_cast_57 = {{2{winograd_d_fixpt_m3_2[13]}}, winograd_d_fixpt_m3_2};
  assign winograd_d_fixpt_add_temp_25 = winograd_d_fixpt_add_cast_56 + winograd_d_fixpt_add_cast_57;
  assign winograd_d_fixpt_m1_3 = winograd_d_fixpt_add_temp_25[13:0];
  assign winograd_d_fixpt_sub_cast_41 = {winograd_d_fixpt_m2_3[13], winograd_d_fixpt_m2_3};
  assign winograd_d_fixpt_sub_cast_42 = {winograd_d_fixpt_m3_2[13], winograd_d_fixpt_m3_2};
  assign winograd_d_fixpt_sub_temp_16 = winograd_d_fixpt_sub_cast_41 - winograd_d_fixpt_sub_cast_42;
  assign winograd_d_fixpt_sub_cast_43 = {winograd_d_fixpt_sub_temp_16[14], winograd_d_fixpt_sub_temp_16};
  assign winograd_d_fixpt_sub_cast_44 = {winograd_d_fixpt_c_4[14], winograd_d_fixpt_c_4};
  assign winograd_d_fixpt_sub_cast_45 = {k12[13], k12};
  assign winograd_d_fixpt_sub_cast_46 = {k8[13], k8};
  assign winograd_d_fixpt_sub_temp_17 = winograd_d_fixpt_sub_cast_45 - winograd_d_fixpt_sub_cast_46;
  assign winograd_d_fixpt_sub_cast_47 = {winograd_d_fixpt_sub_temp_17[14], winograd_d_fixpt_sub_temp_17};
  assign winograd_d_fixpt_sub_temp_18 = winograd_d_fixpt_sub_cast_44 - winograd_d_fixpt_sub_cast_47;
  assign winograd_d_fixpt_mul_temp_9 = winograd_d_fixpt_sub_temp_18 * winograd_d_fixpt_g_3_3;
  assign winograd_d_fixpt_sub_cast_48 = winograd_d_fixpt_mul_temp_9[25:12];
  assign winograd_d_fixpt_sub_cast_49 = {{2{winograd_d_fixpt_sub_cast_48[13]}}, winograd_d_fixpt_sub_cast_48};
  assign winograd_d_fixpt_sub_temp_19 = winograd_d_fixpt_sub_cast_43 - winograd_d_fixpt_sub_cast_49;
  assign winograd_d_fixpt_m2_3_1 = winograd_d_fixpt_sub_temp_19[13:0];
  assign winograd_d_fixpt_sub_cast_50 = {k6[13], k6};
  assign winograd_d_fixpt_sub_cast_51 = {k14[13], k14};
  assign winograd_d_fixpt_c_6 = winograd_d_fixpt_sub_cast_50 - winograd_d_fixpt_sub_cast_51;
  assign winograd_d_fixpt_sub_cast_52 = {k7[13], k7};
  assign winograd_d_fixpt_sub_cast_53 = {k15[13], k15};
  assign winograd_d_fixpt_c_7 = winograd_d_fixpt_sub_cast_52 - winograd_d_fixpt_sub_cast_53;
  // r=winograd_s([1,2,3,4],[1,2,3])
  // g_=zeros(1,4);
  // m=zeros(1,4);
  // r=zeros(1,2);
  // 
  // r=int16(r);
  // m=int16(m);
  // g_=int16(g_);
  // 
  // g_(1)=g(1);
  // g_(2)=(g(1)+g(2)+g(3))/2;
  // g_(3)=(g(1)-g(2)+g(3))/2;
  // g_(4)=g(3);
  // 
  // 
  //     m(1)=(d(1)-d(3))*g_(1);
  //     m(2)=(d(2)+d(3))*g_(2);
  //     m(3)=(d(3)-d(2))*g_(3);
  //     m(4)=(d(2)-d(4))*g_(4);
  //     r(1)=m(1)+m(2)+m(3);
  //     r(2)=m(2)-m(3)-m(4);
  assign winograd_d_fixpt_add_cast_58 = {winograd_d_fixpt_c_6[14], winograd_d_fixpt_c_6};
  assign winograd_d_fixpt_add_cast_59 = {winograd_d_fixpt_c_7[14], winograd_d_fixpt_c_7};
  assign winograd_d_fixpt_add_temp_26 = winograd_d_fixpt_add_cast_58 + winograd_d_fixpt_add_cast_59;
  assign winograd_d_fixpt_add_cast_60 = {w7[13], w7};
  assign winograd_d_fixpt_add_cast_61 = {w8[13], w8};
  assign winograd_d_fixpt_add_temp_27 = winograd_d_fixpt_add_cast_60 + winograd_d_fixpt_add_cast_61;
  assign winograd_d_fixpt_add_cast_62 = {winograd_d_fixpt_add_temp_27[14], winograd_d_fixpt_add_temp_27};
  assign winograd_d_fixpt_add_cast_63 = {{2{w9[13]}}, w9};
  assign winograd_d_fixpt_add_temp_28 = winograd_d_fixpt_add_cast_62 + winograd_d_fixpt_add_cast_63;
  assign winograd_d_fixpt_cast_31 = {winograd_d_fixpt_add_temp_28, 1'b0};
  assign winograd_d_fixpt_cast_32 = winograd_d_fixpt_cast_31 >>> 8'd1;
  assign winograd_d_fixpt_cast_33 = winograd_d_fixpt_cast_32[16:3];
  assign winograd_d_fixpt_mul_temp_10 = winograd_d_fixpt_add_temp_26 * winograd_d_fixpt_cast_33;
  assign winograd_d_fixpt_m2_4 = winograd_d_fixpt_mul_temp_10[24:11];
  assign winograd_d_fixpt_sub_cast_54 = {winograd_d_fixpt_c_7[14], winograd_d_fixpt_c_7};
  assign winograd_d_fixpt_sub_cast_55 = {winograd_d_fixpt_c_6[14], winograd_d_fixpt_c_6};
  assign winograd_d_fixpt_sub_temp_20 = winograd_d_fixpt_sub_cast_54 - winograd_d_fixpt_sub_cast_55;
  assign winograd_d_fixpt_sub_cast_56 = {w7[13], w7};
  assign winograd_d_fixpt_sub_cast_57 = {w8[13], w8};
  assign winograd_d_fixpt_sub_temp_21 = winograd_d_fixpt_sub_cast_56 - winograd_d_fixpt_sub_cast_57;
  assign winograd_d_fixpt_add_cast_64 = {winograd_d_fixpt_sub_temp_21[14], winograd_d_fixpt_sub_temp_21};
  assign winograd_d_fixpt_add_cast_65 = {{2{w9[13]}}, w9};
  assign winograd_d_fixpt_add_temp_29 = winograd_d_fixpt_add_cast_64 + winograd_d_fixpt_add_cast_65;
  assign winograd_d_fixpt_cast_34 = {winograd_d_fixpt_add_temp_29, 1'b0};
  assign winograd_d_fixpt_cast_35 = winograd_d_fixpt_cast_34 >>> 8'd1;
  assign winograd_d_fixpt_cast_36 = winograd_d_fixpt_cast_35[16:3];
  assign winograd_d_fixpt_mul_temp_11 = winograd_d_fixpt_sub_temp_20 * winograd_d_fixpt_cast_36;
  assign winograd_d_fixpt_m3_3 = winograd_d_fixpt_mul_temp_11[24:11];
  assign winograd_d_fixpt_sub_cast_58 = {k1[13], k1};
  assign winograd_d_fixpt_sub_cast_59 = {k9[13], k9};
  assign winograd_d_fixpt_sub_temp_22 = winograd_d_fixpt_sub_cast_58 - winograd_d_fixpt_sub_cast_59;
  assign winograd_d_fixpt_sub_cast_60 = {winograd_d_fixpt_sub_temp_22[14], winograd_d_fixpt_sub_temp_22};
  assign winograd_d_fixpt_sub_cast_61 = {winograd_d_fixpt_c_1[14], winograd_d_fixpt_c_1};
  assign winograd_d_fixpt_sub_temp_23 = winograd_d_fixpt_sub_cast_60 - winograd_d_fixpt_sub_cast_61;
  assign winograd_d_fixpt_cast_37 = {w1[13], w1[13:1]};
  assign winograd_d_fixpt_mul_temp_12 = winograd_d_fixpt_sub_temp_23 * winograd_d_fixpt_cast_37;
  assign winograd_d_fixpt_add_cast_66 = winograd_d_fixpt_mul_temp_12[25:12];
  assign winograd_d_fixpt_add_cast_67 = {winograd_d_fixpt_add_cast_66[13], winograd_d_fixpt_add_cast_66};
  assign winograd_d_fixpt_add_cast_68 = {winograd_d_fixpt_m2[13], winograd_d_fixpt_m2};
  assign winograd_d_fixpt_add_temp_30 = winograd_d_fixpt_add_cast_67 + winograd_d_fixpt_add_cast_68;
  assign winograd_d_fixpt_add_cast_69 = {winograd_d_fixpt_add_temp_30[14], winograd_d_fixpt_add_temp_30};
  assign winograd_d_fixpt_add_cast_70 = {{2{winograd_d_fixpt_m3[13]}}, winograd_d_fixpt_m3};
  assign winograd_d_fixpt_add_temp_31 = winograd_d_fixpt_add_cast_69 + winograd_d_fixpt_add_cast_70;
  assign winograd_d_fixpt_add_cast_71 = winograd_d_fixpt_add_temp_31[13:0];
  assign winograd_d_fixpt_add_cast_72 = {winograd_d_fixpt_add_cast_71[13], winograd_d_fixpt_add_cast_71};
  assign winograd_d_fixpt_add_cast_73 = {winograd_d_fixpt_m1_2[13], winograd_d_fixpt_m1_2};
  assign winograd_d_fixpt_add_temp_32 = winograd_d_fixpt_add_cast_72 + winograd_d_fixpt_add_cast_73;
  assign winograd_d_fixpt_add_cast_74 = {winograd_d_fixpt_add_temp_32[14], winograd_d_fixpt_add_temp_32};
  assign winograd_d_fixpt_add_cast_75 = {{2{winograd_d_fixpt_m1_3[13]}}, winograd_d_fixpt_m1_3};
  assign winograd_d_fixpt_add_temp_33 = winograd_d_fixpt_add_cast_74 + winograd_d_fixpt_add_cast_75;
  assign R1 = winograd_d_fixpt_add_temp_33[13:0];
  assign winograd_d_fixpt_add_cast_76 = {winograd_d_fixpt_m2_1[13], winograd_d_fixpt_m2_1};
  assign winograd_d_fixpt_sub_cast_62 = {winograd_d_fixpt_m2_2[13], winograd_d_fixpt_m2_2};
  assign winograd_d_fixpt_sub_cast_63 = {winograd_d_fixpt_m3_1[13], winograd_d_fixpt_m3_1};
  assign winograd_d_fixpt_sub_temp_24 = winograd_d_fixpt_sub_cast_62 - winograd_d_fixpt_sub_cast_63;
  assign winograd_d_fixpt_sub_cast_64 = {winograd_d_fixpt_sub_temp_24[14], winograd_d_fixpt_sub_temp_24};
  assign winograd_d_fixpt_sub_cast_65 = {winograd_d_fixpt_c_2[14], winograd_d_fixpt_c_2};
  assign winograd_d_fixpt_add_cast_77 = {k8[13], k8};
  assign winograd_d_fixpt_add_cast_78 = {k12[13], k12};
  assign winograd_d_fixpt_add_temp_34 = winograd_d_fixpt_add_cast_77 + winograd_d_fixpt_add_cast_78;
  assign winograd_d_fixpt_sub_cast_66 = {winograd_d_fixpt_add_temp_34[14], winograd_d_fixpt_add_temp_34};
  assign winograd_d_fixpt_sub_temp_25 = winograd_d_fixpt_sub_cast_65 - winograd_d_fixpt_sub_cast_66;
  assign winograd_d_fixpt_mul_temp_13 = winograd_d_fixpt_sub_temp_25 * winograd_d_fixpt_g_3_2;
  assign winograd_d_fixpt_sub_cast_67 = winograd_d_fixpt_mul_temp_13[25:12];
  assign winograd_d_fixpt_sub_cast_68 = {{2{winograd_d_fixpt_sub_cast_67[13]}}, winograd_d_fixpt_sub_cast_67};
  assign winograd_d_fixpt_sub_temp_26 = winograd_d_fixpt_sub_cast_64 - winograd_d_fixpt_sub_cast_68;
  assign winograd_d_fixpt_add_cast_79 = winograd_d_fixpt_sub_temp_26[13:0];
  assign winograd_d_fixpt_add_cast_80 = {winograd_d_fixpt_add_cast_79[13], winograd_d_fixpt_add_cast_79};
  assign winograd_d_fixpt_add_temp_35 = winograd_d_fixpt_add_cast_76 + winograd_d_fixpt_add_cast_80;
  assign winograd_d_fixpt_add_cast_81 = {winograd_d_fixpt_add_temp_35[14], winograd_d_fixpt_add_temp_35};
  assign winograd_d_fixpt_add_cast_82 = {{2{winograd_d_fixpt_m2_3_1[13]}}, winograd_d_fixpt_m2_3_1};
  assign winograd_d_fixpt_add_temp_36 = winograd_d_fixpt_add_cast_81 + winograd_d_fixpt_add_cast_82;
  assign R2 = winograd_d_fixpt_add_temp_36[13:0];
  assign winograd_d_fixpt_sub_cast_69 = {winograd_d_fixpt_m1_2[13], winograd_d_fixpt_m1_2};
  assign winograd_d_fixpt_sub_cast_70 = {winograd_d_fixpt_m1_3[13], winograd_d_fixpt_m1_3};
  assign winograd_d_fixpt_sub_temp_27 = winograd_d_fixpt_sub_cast_69 - winograd_d_fixpt_sub_cast_70;
  assign winograd_d_fixpt_sub_cast_71 = {winograd_d_fixpt_sub_temp_27[14], winograd_d_fixpt_sub_temp_27};
  assign winograd_d_fixpt_sub_cast_72 = {k5[13], k5};
  assign winograd_d_fixpt_sub_cast_73 = {k13[13], k13};
  assign winograd_d_fixpt_sub_temp_28 = winograd_d_fixpt_sub_cast_72 - winograd_d_fixpt_sub_cast_73;
  assign winograd_d_fixpt_sub_cast_74 = {winograd_d_fixpt_sub_temp_28[14], winograd_d_fixpt_sub_temp_28};
  assign winograd_d_fixpt_sub_cast_75 = {winograd_d_fixpt_c_7[14], winograd_d_fixpt_c_7};
  assign winograd_d_fixpt_sub_temp_29 = winograd_d_fixpt_sub_cast_74 - winograd_d_fixpt_sub_cast_75;
  assign winograd_d_fixpt_cast_38 = {w7[13], w7[13:1]};
  assign winograd_d_fixpt_mul_temp_14 = winograd_d_fixpt_sub_temp_29 * winograd_d_fixpt_cast_38;
  assign winograd_d_fixpt_add_cast_83 = winograd_d_fixpt_mul_temp_14[25:12];
  assign winograd_d_fixpt_add_cast_84 = {winograd_d_fixpt_add_cast_83[13], winograd_d_fixpt_add_cast_83};
  assign winograd_d_fixpt_add_cast_85 = {winograd_d_fixpt_m2_4[13], winograd_d_fixpt_m2_4};
  assign winograd_d_fixpt_add_temp_37 = winograd_d_fixpt_add_cast_84 + winograd_d_fixpt_add_cast_85;
  assign winograd_d_fixpt_add_cast_86 = {winograd_d_fixpt_add_temp_37[14], winograd_d_fixpt_add_temp_37};
  assign winograd_d_fixpt_add_cast_87 = {{2{winograd_d_fixpt_m3_3[13]}}, winograd_d_fixpt_m3_3};
  assign winograd_d_fixpt_add_temp_38 = winograd_d_fixpt_add_cast_86 + winograd_d_fixpt_add_cast_87;
  assign winograd_d_fixpt_sub_cast_76 = winograd_d_fixpt_add_temp_38[13:0];
  assign winograd_d_fixpt_sub_cast_77 = {{2{winograd_d_fixpt_sub_cast_76[13]}}, winograd_d_fixpt_sub_cast_76};
  assign winograd_d_fixpt_sub_temp_30 = winograd_d_fixpt_sub_cast_71 - winograd_d_fixpt_sub_cast_77;
  assign R3 = winograd_d_fixpt_sub_temp_30[13:0];
  assign winograd_d_fixpt_sub_cast_78 = {winograd_d_fixpt_m2_1[13], winograd_d_fixpt_m2_1};
  assign winograd_d_fixpt_sub_cast_79 = {winograd_d_fixpt_m2_3_1[13], winograd_d_fixpt_m2_3_1};
  assign winograd_d_fixpt_sub_temp_31 = winograd_d_fixpt_sub_cast_78 - winograd_d_fixpt_sub_cast_79;
  assign winograd_d_fixpt_sub_cast_80 = {winograd_d_fixpt_sub_temp_31[14], winograd_d_fixpt_sub_temp_31};
  assign winograd_d_fixpt_sub_cast_81 = {winograd_d_fixpt_m2_4[13], winograd_d_fixpt_m2_4};
  assign winograd_d_fixpt_sub_cast_82 = {winograd_d_fixpt_m3_3[13], winograd_d_fixpt_m3_3};
  assign winograd_d_fixpt_sub_temp_32 = winograd_d_fixpt_sub_cast_81 - winograd_d_fixpt_sub_cast_82;
  assign winograd_d_fixpt_sub_cast_83 = {winograd_d_fixpt_sub_temp_32[14], winograd_d_fixpt_sub_temp_32};
  assign winograd_d_fixpt_sub_cast_84 = {winograd_d_fixpt_c_6[14], winograd_d_fixpt_c_6};
  assign winograd_d_fixpt_sub_cast_85 = {k2[13], k2};
  assign winograd_d_fixpt_sub_cast_86 = {k16[13], k16};
  assign winograd_d_fixpt_sub_temp_33 = winograd_d_fixpt_sub_cast_85 - winograd_d_fixpt_sub_cast_86;
  assign winograd_d_fixpt_sub_cast_87 = {winograd_d_fixpt_sub_temp_33[14], winograd_d_fixpt_sub_temp_33};
  assign winograd_d_fixpt_sub_temp_34 = winograd_d_fixpt_sub_cast_84 - winograd_d_fixpt_sub_cast_87;
  assign winograd_d_fixpt_cast_39 = {w9[13], w9[13:1]};
  assign winograd_d_fixpt_mul_temp_15 = winograd_d_fixpt_sub_temp_34 * winograd_d_fixpt_cast_39;
  assign winograd_d_fixpt_sub_cast_88 = winograd_d_fixpt_mul_temp_15[25:12];
  assign winograd_d_fixpt_sub_cast_89 = {{2{winograd_d_fixpt_sub_cast_88[13]}}, winograd_d_fixpt_sub_cast_88};
  assign winograd_d_fixpt_sub_temp_35 = winograd_d_fixpt_sub_cast_83 - winograd_d_fixpt_sub_cast_89;
  assign winograd_d_fixpt_sub_cast_90 = winograd_d_fixpt_sub_temp_35[13:0];
  assign winograd_d_fixpt_sub_cast_91 = {{2{winograd_d_fixpt_sub_cast_90[13]}}, winograd_d_fixpt_sub_cast_90};
  assign winograd_d_fixpt_sub_temp_36 = winograd_d_fixpt_sub_cast_80 - winograd_d_fixpt_sub_cast_91;
  assign R4 = winograd_d_fixpt_sub_temp_36[13:0];



endmodule  // winograd_d_fixpt

