# ----------------------------------------
# Created on: Tue Feb 28 15:09:09 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vlog   "C:/Users/FH/Desktop/conv3x3-bing/source/Desktop/conv.v" -work work
vlog   "C:/Users/FH/Desktop/conv3x3-bing/source/Desktop/line_buffer.v" -work work
vlog   "C:/Users/FH/Desktop/conv3x3-bing/source/matrix_3x3/source/Desktop/line_buffer.v" -work work
vlog   "C:/Users/FH/Desktop/conv3x3-bing/ipcore/fifo0/rtl/ipm_distributed_fifo_ctr_v1_0.v" -work work
vlog   "C:/Users/FH/Desktop/conv3x3-bing/ipcore/fifo0/rtl/ipm_distributed_fifo_v1_2_fifo0.v" -work work
vlog   "C:/Users/FH/Desktop/conv3x3-bing/ipcore/fifo0/rtl/ipm_distributed_sdpram_v1_2_fifo0.v" -work work
vlog   "C:/Users/FH/Desktop/conv3x3-bing/ipcore/fifo0/fifo0.v" -work work
vlog   "C:/Users/FH/Desktop/conv3x3-bing/source/Desktop/conv_tb.v" -work work

# ----------------------------------------
