# ----------------------------------------
# Created on: Tue Feb 28 15:03:56 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vlog   "C:/Users/FH/Desktop/matrix_3x3/source/Desktop/line_buffer.v" -work work
vlog   "C:/Users/FH/Desktop/matrix_3x3/source/FH/Desktop/line_buffer.v" -work work
vlog   "C:/Users/FH/Desktop/matrix_3x3/ipcore/fifo_0/rtl/ipm_distributed_fifo_ctr_v1_0.v" -work work
vlog   "C:/Users/FH/Desktop/matrix_3x3/ipcore/fifo_0/rtl/ipm_distributed_fifo_v1_2_fifo_0.v" -work work
vlog   "C:/Users/FH/Desktop/matrix_3x3/ipcore/fifo_0/rtl/ipm_distributed_sdpram_v1_2_fifo_0.v" -work work
vlog   "C:/Users/FH/Desktop/matrix_3x3/ipcore/fifo_0/fifo_0.v" -work work
vlog   "C:/Users/FH/Desktop/matrix_3x3/source/Desktop/matrix_3x3_tb.v" -work work

# ----------------------------------------
