# ----------------------------------------
# Created on: Tue Feb 28 15:03:56 2023
# Auto generated by Pango
# ----------------------------------------

vsim  -voptargs="+acc" -L work matrix_3x3_tb
add wave *
view wave
view structure
view signals

run 100000ns

# ----------------------------------------
