#Generated by Fabric Compiler ( version 2020.3-Lite <build 71107> ) at Tue Feb 28 11:24:04 2023

add_design "C:/Users/FH/Desktop/wino/source/Desktop/winograd_d_fixpt.v"
add_simulation "C:/Users/FH/Desktop/wino/source/Desktop/wino_tb.v"
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module winograd_d_fixpt
synthesize -ads -selected_syn_tool_opt 2 
