#Generated by Fabric Compiler ( version 2020.3-Lite <build 71107> ) at Sun Feb 26 22:50:46 2023

add_design "C:/Users/FH/Desktop/conv3x3/source/Desktop/conv.v"
add_design "C:/Users/FH/Desktop/conv3x3/source/Desktop/matrix_3x3.v"
add_design C:/Users/FH/Desktop/conv3x3/ipcore/fifo0/fifo0.idf
add_design "C:/Users/FH/Desktop/conv3x3/source/Desktop/line_buffer.v"
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
remove_design -verilog "C:/Users/FH/Desktop/conv3x3/source/Desktop/matrix_3x3.v"
add_design "C:/Users/FH/Desktop/conv3x3/source/source/Desktop/line_buffer.v"
add_design "C:/Users/FH/Desktop/conv3x3/source/Desktop/matrix_3x3_tb.v"
remove_design -verilog "C:/Users/FH/Desktop/conv3x3/source/source/Desktop/line_buffer.v"
add_design "C:/Users/FH/Desktop/conv3x3/source/matrix_3x3/source/Desktop/line_buffer.v"
add_design "C:/Users/FH/Desktop/conv3x3/source/source/Desktop/matrix_3x3_tb.v"
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
remove_design -verilog "C:/Users/FH/Desktop/conv3x3/source/Desktop/matrix_3x3_tb.v"
remove_design -verilog "C:/Users/FH/Desktop/conv3x3/source/source/Desktop/matrix_3x3_tb.v"
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
add_simulation "C:/Users/FH/Desktop/conv3x3/source/Desktop/conv_tb.v"
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module conv
synthesize -ads -selected_syn_tool_opt 2 
