#Generated by Fabric Compiler ( version 2020.3-Lite <build 71107> ) at Sun Feb 26 11:52:14 2023

add_design "C:/Users/FH/Desktop/matrix_3x3/source/Desktop/matrix_3x3.v"
add_design "C:/Users/FH/Desktop/matrix_3x3/source/Desktop/matrix_3x3_tb.v"
remove_design -verilog "C:/Users/FH/Desktop/matrix_3x3/source/Desktop/matrix_3x3_tb.v"
add_design C:/Users/FH/Desktop/matrix_3x3/ipcore/fifo_0/fifo_0.idf
add_design "C:/Users/FH/Desktop/matrix_3x3/source/Desktop/line_buffer.v"
add_design "C:/Users/FH/Desktop/matrix_3x3/source/FH/Desktop/line_buffer.v"
remove_design -verilog "C:/Users/FH/Desktop/matrix_3x3/source/FH/Desktop/line_buffer.v"
remove_design -verilog "C:/Users/FH/Desktop/matrix_3x3/source/Desktop/line_buffer.v"
remove_design -verilog "C:/Users/FH/Desktop/matrix_3x3/source/Desktop/matrix_3x3.v"
remove_design -verilog "C:/Users/FH/Desktop/matrix_3x3/source/Desktop/matrix_3x3.v"
add_design "C:/Users/FH/Desktop/matrix_3x3/source/Users/FH/Desktop/line_buffer.v"
remove_design -verilog "C:/Users/FH/Desktop/matrix_3x3/source/Users/FH/Desktop/line_buffer.v"
add_design "C:/Users/FH/Desktop/matrix_3x3/source/Desktop/line_buffer.v"
add_design "C:/Users/FH/Desktop/matrix_3x3/source/FH/Desktop/line_buffer.v"
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module matrix_3x3
add_simulation "C:/Users/FH/Desktop/matrix_3x3/source/Desktop/matrix_3x3_tb.v"
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module matrix_3x3
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module matrix_3x3
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module matrix_3x3
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module matrix_3x3
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module matrix_3x3
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module matrix_3x3
set_arch -family Logos -device PGL22G -speedgrade -7 -package MBG324
compile -top_module matrix_3x3
